### ISSUE TITLE
Error: "Your requirements could not be resolved to an installable set of packages"

### ISSUE THREAD

**Issue by marcosvolpiok** [mtrajano/laravel-swagger#37] opened 2020-02-20 15:38 UTC
- Laravel Swagger Version: v0.6.3
- Laravel Version: 6.16.0
- PHP Version: 7.3.10

When I try to install with the follow command: 
composer require mtrajano/laravel-swagger
I get the follow error:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove phpdocumentor/reflection-common 2.0.0
    - Conclusion: don't install phpdocumentor/reflection-common 2.0.0
    - phpdocumentor/reflection-docblock 4.3.0 requires phpdocumentor/reflection-common ^1.0.0 -> satisfiable by phpdocumentor/reflection-common[1.0, 1.0.1].
    - phpdocumentor/reflection-docblock 4.3.1 requires phpdocumentor/reflection-common ^1.0.0 -> satisfiable by phpdocumentor/reflection-common[1.0, 1.0.1].
    - Can only install one of: phpdocumentor/reflection-common[1.0, 2.0.0].
    - Can only install one of: phpdocumentor/reflection-common[1.0.1, 2.0.0].
    - Installation request for phpdocumentor/reflection-common (locked at 2.0.0) -> satisfiable by phpdocumentor/reflection-common[2.0.0].
    - Installation request for mtrajano/laravel-swagger ^0.6.3 -> satisfiable by mtrajano/laravel-swagger[v0.6.3].
    - Conclusion: don't install phpdocumentor/reflection-docblock 5.0.0|install phpdocumentor/reflection-docblock 4.3.0|install phpdocumentor/reflection-docblock 4.3.1
    - Conclusion: remove phpdocumentor/reflection-docblock 5.0.0|install phpdocumentor/reflection-docblock 4.3.0|install phpdocumentor/reflection-docblock 4.3.1
    - mtrajano/laravel-swagger v0.6.3 requires phpdocumentor/reflection-docblock ^4.3 -> satisfiable by phpdocumentor/reflection-docblock[4.3.0, 4.3.1, 4.3.2, 4.3.3, 4.3.4].
    - Can only install one of: phpdocumentor/reflection-docblock[4.3.2, 5.0.0].
    - Can only install one of: phpdocumentor/reflection-docblock[4.3.3, 5.0.0].
    - Can only install one of: phpdocumentor/reflection-docblock[4.3.4, 5.0.0].
    - Installation request for phpdocumentor/reflection-docblock (locked at 5.0.0) -> satisfiable by phpdocumentor/reflection-docblock[5.0.0].

How to fix that?

Thanks.

**Comment by mtrajano** [comment] 2020-03-28 16:02
Looks like you have a conflict in your composer.json either you or another one of your packages is requiring `reflection-docblock 5.0` while this package requires `^4.3`. Something I'll potentially upgrade in the future but not a priority right now. Closing as this is not a bug in this package per se.

**Closed by mtrajano** 2020-03-28 16:02 UTC
Labels: bug

**Comment by nickpoulos** [comment] 2020-05-26 17:28
Hey @mtrajano any chance you would consider re-opening this issue? We are also running into this issue, it seems a fresh Laravel install can no longer use this package because phpunit/phpunit 8.5.2 requires phpspec/prophecy
